Added style for Counter component
isdi-coders-202207-bcn-coding-adventure/cristian-sarroca-front pull request #3
Opened 2022-08-22 15:10 UTC by Csarroca

2022-08-23 07:02 UTC, luisdudamel requested changes

2022-08-23 07:02 UTC, luisdudamel commented on src/components/Counter/StyledCounter.tsx
> +  .counter-input__text {
Hola Cristian,
Una de las ventajas de styled components, es que podemos anidar selectores que comienzan por la misma palabra, para no repetir codigo.

2022-08-23 08:45 UTC, Csarroca commented on src/components/Counter/StyledCounter.tsx
> +  .counter-input__text {
Ok,  gracias Luis.

2022-08-23 11:12 UTC, luisdudamel approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-23 11:32 UTC, merged

2022-08-24 15:33 UTC, AdrianArmestoMena commented on src/components/Counter/StyledCounter.tsx
> +  flex-direction: row;
flex-direction row te lo podrías ahorrar, la propiedad ya viene implícita.

2022-08-24 15:44 UTC, Csarroca commented on src/components/Counter/StyledCounter.tsx
> +  flex-direction: row;
Gracias compi por tus consejos. Lo tendré en cuenta!

2022-08-24 15:48 UTC, Csarroca commented on src/components/Counter/StyledCounter.tsx
> +  flex-direction: row;
Gracias!